### ISSUE TITLE
how can I used in interllij

### ISSUE THREAD

**Issue by shufanhao** [dave-tucker/intellij-yang#3]
how can I use your code in interllij so that intellij can support yang file writing.

**Comment by dave-tucker** [comment]
There are some (rather old) instructions [here](https://github.com/dave-tucker/intellij-yang/releases)

**Comment by pillravi** [comment]
A bit more detailed instructions are available [here](https://www.jetbrains.com/help/idea/2016.3/installing-plugin-from-disk.html); follow Dave's link for the .jar.
