### ISSUE TITLE
will intellij-yang support the features yang-ide have?

### ISSUE THREAD

**Issue by Jack2code** [dave-tucker/intellij-yang#4]
* [M2E Integration] (M2E Integration)
  * Import maven project
  * Handle `yang-maven-plugin` lifecycle
* [Yang Project Support] (Yang Project Support)
  * New YANG File Wizard
  * New YANG Project Wizard 
  * Yang Code Syntax Validation
  * Yang Code Semantic Validation  
* [Code Editing] (Code Editing)
  * Syntax Highlight
  * Semantic Highlight
  * Documentation Hover
  * Code Completion
  * Smart Paste
  * Code Formatter
  * Toggle Comment
  * Code Templates
* [Code Navigation] (Code Navigation)
  * Code Folding
  * Code Outline
  * Hyperlink navigation
  * Goto declaration
* [Code Refactoring] (Code Refactoring)
  * Rename Refactoring
  * Inline Grouping
  * Extract Grouping
  * Change Revision
* [Diagram Model Editor] (Diagram Editor)
  * 2-way synchronization between source code and diagram view
  * Update YANG element properties from diagram view
  * Visual decoration of YANG hierarchy and `uses` relationship

**Comment by Jack2code** [comment]
yang ide feature link: https://github.com/xored/yang-ide/wiki/Features

**Comment by dave-tucker** [comment]
Not unless somebody plans on contributing them - I haven't needed to work with Yang for over a year or more so I'm not actively maintaining this plugin, although I'm doing my best to merge any PR's that are made.
